### ISSUE TITLE
getOctokit

### ISSUE THREAD

**Issue by cquiroz** [singingwolfboy/create-linked-clubhouse-story#3]
Today I tried to create a PR with the action installed but got this error

```
Run singingwolfboy/create-linked-clubhouse-story@v1.4
(node:2618) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getOctokit' of undefined
    at Object.<anonymous> (/home/runner/work/_actions/singingwolfboy/create-linked-clubhouse-story/v1.4/dist/index.js:513:42)
        at Generator.next (<anonymous>)
    at /home/runner/work/_actions/singingwolfboy/create-linked-clubhouse-story/v1.4/dist/index.js:274:71
       at new Promise (<anonymous>)
    at module.exports.__webpack_modules__.24.__awaiter (/home/runner/work/_actions/singingwolfboy/create-linked-clubhouse-story/v1.4/dist/index.js:270:12)
        at Object.getClubhouseURLFromPullRequest (/home/runner/work/_actions/singingwolfboy/create-linked-clubhouse-story/v1.4/dist/index.js:503:12)
    at Object.<anonymous> (/home/runner/work/_actions/singingwolfboy/create-linked-clubhouse-story/v1.4/dist/index.js:219:43)
        at Generator.next (<anonymous>)
    at /home/runner/work/_actions/singingwolfboy/create-linked-clubhouse-story/v1.4/dist/index.js:197:71
       at new Promise (<anonymous>)
	(node:2618) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```
I wonder if I should install some lib before running the action?

**Comment by singingwolfboy** [comment]
@cquiroz Thanks for pointing that out! Apparently the `npm run pack` command didn't run correctly the first time. [I repacked the project and created a new commit](https://github.com/singingwolfboy/create-linked-clubhouse-story/commit/311b5e3feb20ddaa122576910bd778d91cf96b5f), and updated the `v1.4` tag to point to it. Can you verify that it works for you now? You shouldn't need to do anything different.

**Comment by cquiroz** [comment]
Thanks a lot, now it is working great.
